a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
print("Input numbers are:",a,b)
print("Addition:",a+b)
print("Substraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)